language: python
python:
***REMOVED***- 2.6
***REMOVED***- 2.7
***REMOVED***- 3.3
***REMOVED***- 3.4
***REMOVED***- 3.5
***REMOVED***- 3.6
script:
***REMOVED***- coverage run --source=createsend nosetests.py
***REMOVED***- coverage report
sudo: false
