language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install coverage coveralls
script:
  - coverage run --source=lib setup.py test
  - coverage report
  - coveralls
sudo: false
