language: python
python:
***REMOVED***- 3.6
***REMOVED***- 3.7
***REMOVED***- 3.8
***REMOVED***- 3.9
***REMOVED***- 3.10
***REMOVED***- 3.11
***REMOVED***- 3.12
***REMOVED***- 3.13
install:
***REMOVED***- pip install coverage coveralls
script:
***REMOVED***- coverage run --source=lib setup.py test
***REMOVED***- coverage report
***REMOVED***- coveralls
sudo: false
