language: python
python:
***REMOVED***- 2.7
***REMOVED***- 3.4
***REMOVED***- 3.5
***REMOVED***- 3.6
***REMOVED***- 3.7
***REMOVED***- 3.8
install:
***REMOVED***- pip install coverage coveralls
script:
***REMOVED***- coverage run --source=lib setup.py test
***REMOVED***- coverage report
***REMOVED***- coveralls
sudo: false
