language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - 3.10
  - 3.11
  - 3.12
  - 3.13
install:
  - pip install coverage coveralls
script:
  - coverage run --source=lib setup.py test
  - coverage report
  - coveralls
sudo: false
